# -*- coding: utf-8 -*-
from . import univ_room
from . import univ_timeslot
from . import univ_academic_calendar
from . import univ_plo
from . import univ_clo
from . import univ_syllabus
from . import univ_lesson_plan
from . import univ_timetable_session
from . import univ_timetable_substitution
from . import univ_attendance_sheet
from . import univ_attendance_summary
from . import univ_exam_type
from . import univ_grade_scale
from . import univ_exam
from . import univ_exam_schedule
from . import univ_exam_invigilator
from . import univ_exam_seat
from . import univ_exam_result_line
from . import univ_exam_reevaluation
from . import univ_result_semester
from . import univ_result_transcript
from . import univ_section
from . import univ_subject
from . import univ_faculty
from . import univ_student
from . import univ_subject_prerequisite
from . import univ_registration_period
from . import univ_course_offering
from . import univ_course_registration
from . import univ_student_registration
