from . import document_annotation
from . import document_dashboard
from . import document_document
from . import document_folder
from . import document_request
from . import document_tag
from . import document_version
from . import document_wizard
from . import document_workspace
from . import res_config_settings
