# -*- coding: utf-8 -*-
from . import res_company
from . import res_config_settings
from . import univ_fee_group
from . import univ_academic_session
from . import univ_fee_quota
from . import univ_fee_category
from . import univ_fee_head
from . import univ_fee_structure
from . import univ_fee_invoice
from . import univ_fee_installment_plan
from . import univ_fee_refund_request
from . import univ_fee_waiver
from . import univ_scholarship_scheme
from . import univ_scholarship_award
from . import univ_fee_reminder_log
from . import univ_student
from . import univ_applicant
from . import account_move
from . import univ_fee_structure_deposit
from . import univ_applicant_deposit
