from . import asset_category
from . import asset_location
from . import asset
from . import asset_transfer
from . import maintenance_request
from . import work_order
from . import work_permit
from . import inspection
from . import asset_meter
from . import maintenance_plan
from . import asset_depreciation
from . import res_config_settings
